### ISSUE TITLE
Is it possible to jump to a wrong spell word? 

### ISSUE THREAD

**Issue by AtsushiSakai** [kamykn/spelunker.vim#1]
Thank you for great plugin. I love it.

I have a question. 
Is there any command or shortcut to jump to a wrong spell word?

Thanks.

**Comment by kamykn** [comment]
Hi, @AtsushiSakai 

This plugin don't have jump function for now, but I think that it is probably not a difficult implementation.

If I could find the time, I'll add jump function to this plugin. But now it may be necessary to add whitelist of other programming language.

**Comment by AtsushiSakai** [comment]
@kamykn OK. Thank you.
