### ISSUE TITLE
Incorrect spelling indication

### ISSUE THREAD

**Issue by sQVe** [kamykn/spelunker.vim#10]
I quickly noted that ***spelunker*** incorrectly marks parts of correct words as misspelled. An example is:
```
format
doormat
ormat
```
***spelunker*** will indicate that all words are misspelled here with `ormat`. This makes the plugin **very hard** to use as it marks a lot of places. 

---

I've also noted that it at times incorrectly marks words as misspelled like:

```vim
" Show documentation.
function! ShowDocumention()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocActionAsync('doHover')
  endif
endfunction
```
***spelunker*** will mark `Documentation` in the function declaration as misspelled here. If I run `Zl` on it nothing happens, as it is already correctly spelled.

**Comment by kamykn** [comment]
@sQVe 
> spelunker will indicate that all words are misspelled here with ormat.

Thank you for your reporting.
This problems are fixed, and now it's better than before!

> spelunker will mark Documentation in the function declaration as misspelled here.

In this case, there were two problems.
One is that `Documention` (not `Documentation`) is judged a misspelled word by the Vim dictionary.
Second, there is a problem when the corrected to 2 words by `spellsuggest()`.

ex) `Documention` -> `Document` `Ion`

The second problem has been fixed.
However, `Documention` is misspelled word in Vim, so add it to your spellfile yourself (`Zg`).

**Comment by sQVe** [comment]
@kamykn Well done. Thank you! I'll test it out tonight! 😀

**Comment by sQVe** [comment]
@kamykn Works as expected now. Nicely done. Closing this issue.

I'd love for `spelunker.vim` to add a command to toggle it on and off. I'll try to add some words to the whitelists and also add a bash whitelist. I'm having a minor go at fixing and formatting the README a bit too.
