### ISSUE TITLE
Command to toggle on and off

### ISSUE THREAD

**Issue by sQVe** [kamykn/spelunker.vim#11]
I check for spelling once in a while and do not want ***spelunker*** to be enabled all the time. It would be great if it would be possible to provide a way to toggle it on and off.

**Comment by kamykn** [comment]
Hi, @sQVe !

Toggle command was added at 3ace12d2d4d3dd511f061ceb6b68aef2baf929b8.
Please update spelunker.vim plug-in and try it.

Document for new command is here.
👉https://github.com/kamykn/spelunker.vim#35-toggle-on-and-off

**Comment by sQVe** [comment]
@kamykn Awesome. Thank you!
