### ISSUE TITLE
Request : mapping for prev/next search like ]s

### ISSUE THREAD

**Issue by tsuyoshicho** [kamykn/spelunker.vim#12]
spell has  jump prev/next

- ]s
- ]S
- [s
- [S

non all replace item need jump check.

**Comment by kamykn** [comment]
Hi, @tsuyoshicho 

 [Jump feature](https://github.com/kamykn/spelunker.vim#34-jump-cursor-to-misspelled-words) was added at d683c26c880b77fa93d0e3ad316e9d0fda92df6c.
Please update `spelunker.vim` plug-in and try it.

If you want override shortcut `[s`, please setting following:
```
nnoremap ]s :call spelunker#jump_next()<CR>
nnoremap [s :call spelunker#jump_prev()<CR>
```

I hope you like it!

**Comment by tsuyoshicho** [comment]
Thanks, This feel is good!!
