### ISSUE TITLE
Spelunker highlight has more priority than the search highlight

### ISSUE THREAD

**Issue by peancored** [kamykn/spelunker.vim#2]
Hi @kamykn, thank you again for the awesome plugin!

I noticed that spelunker's wrong spell highlight has more priority over the search highlight:
![image](https://user-images.githubusercontent.com/5630034/49141949-6d0e3f80-f300-11e8-8b36-faf072f12fa9.png)
![image](https://user-images.githubusercontent.com/5630034/49141974-79929800-f300-11e8-81c1-46b16d59d5ae.png)

This is a bit annoying since I can't see whether a bad spell word belongs to a search result or not.

I checked `set spell` and it doesn't have this issue:
![image](https://user-images.githubusercontent.com/5630034/49141753-06892180-f300-11e8-982b-e40ae09cd626.png)
![image](https://user-images.githubusercontent.com/5630034/49141762-0b4dd580-f300-11e8-9019-1260a4dfb186.png)

Can it be fixed anyhow? 
Thank you!

**Comment by kamykn** [comment]
Hi @peancored, thank you for reporting!
I set the priority of highlight!
Please check it 😆!

**Comment by peancored** [comment]
Muuuch better now, thanks a lot! 🎉
