### ISSUE TITLE
Mismatch of highlighting when toggling

### ISSUE THREAD

**Issue by sQVe** [kamykn/spelunker.vim#21]
Hey :wave:,

There's a mismatch of the highlighted misspelled words when working with multiple windows. Say I have two windows and enable `spelunker`. I then move to the other window and save that file, making `spelunker` highlight the misspelled words. If I then move back to the other window and toggle `spelunker` off it will still highlight in the other window.

When toggling spelunker off we need to reset the highlighting. An even better solution, for my workflow, would be to only enable / disable / toggle spelunker for the active buffer.

**Comment by kamykn** [comment]
Hi @sQVe !

Thank you for your bug report!
Now, this behavior is fixed and added command `Zt` to toggle only current buffer.
Please update plugin and try it!
