### ISSUE TITLE
Feature Request: 'correct spell' item selection use popup

### ISSUE THREAD

**Issue by tsuyoshicho** [kamykn/spelunker.vim#22]
## Suggestion
'correct spell' item selection use popup
Zl/ZL

### Pros:
- command line no expand
- huge count items' selecting at elegance

### Cons:
- fallback to command line at popup no support env.

**Comment by kamykn** [comment]
Hi, @tsuyoshicho !
If popup_menu () is enabled, you can use popup now.
Please update plugin and try it!

#28

**Comment by tsuyoshicho** [comment]
Thanks!! I try it.

**Comment by tsuyoshicho** [comment]
OK, Good It.
