### ISSUE TITLE
broken function args at get_spell_bad_list

### ISSUE THREAD

**Issue by tsuyoshicho** [kamykn/spelunker.vim#37]
> fix issue #20 #34

000e5ef93bb5a48a099a6e8235c4515248845edd 

This commit (merge) broken function argument at get_spell_bad_list.
Error occured.

https://github.com/kamykn/spelunker.vim/blob/8032f749aff995eaa85983edc552949051cec75a/autoload/ctrlp/spelunker.vim#L36

https://github.com/kamykn/spelunker.vim/blob/ce888f123edfb45eaefc259e3a994221737874d0/autoload/spelunker.vim#L49

https://github.com/kamykn/spelunker.vim/blob/ce888f123edfb45eaefc259e3a994221737874d0/autoload/spelunker.vim#L77

after this issue, I PRed fix.

**Comment by kamykn** [comment]
@tsuyoshicho 
Thanks a lot for your pull request!
I apologize for breaking some feature by  my careless code changing.
