### ISSUE TITLE
Some words are not highlighted with spelunker_check_type = 2 or with custom group

### ISSUE THREAD

**Issue by Nodman** [kamykn/spelunker.vim#44]
Hello and thank you for awesome plugin!

I recently installed spelunker on neovim v0.4.3 and noticed strange behaviour:
When using default settings everything works as expected but as soon as I set
`let g:spelunker_check_type = 2`
some incorrectly spelled words stops highlighting. For example I have this test file test.tsx with only two lines:
```
export const isChosed = false;
export const valiateStatus = true;
```
word **"Chosed"** will not be highlighted with settings above but will be highlighted with default settings, word **"valiate"** will be highlighted always, with any settings. This problem also appears when using custom groups (even with default `let g:spelunker_check_type = 1`):

```
let g:spelunker_disable_auto_group = 1

augroup spelunker
  autocmd BufWinEnter,BufWritePost *.js,*.jsx,*.json,*.md,*ts,*tsx call spelunker#check()
augroup END
```

at last: using `let g:spelunker_check_type = 2` will check spelling on some readonly buffers like vim-startify

**Comment by kamykn** [comment]
Hi, @Nodman !
Thank you for using my VIm plugin!

I'm trying to reproduce this problem in my Neovim, but I can't.
This GIF is a screen recording of the NVIM on my MAC.
![nvim-20200525](https://user-images.githubusercontent.com/7608231/82911200-8f8d2180-9fa6-11ea-942f-550b1830408a.gif)

I'm thinking it might be a word that is already on the spelling list.
Could you check if `chosed` is registered in the `~/.config/nvim/spell/en.utf-8.add`?

**Comment by kamykn** [comment]
Or maybe it's the same issue with [this Issue](https://github.com/kamykn/spelunker.vim/issues/35)(#35), so please try updating the plugin.

**Comment by Nodman** [comment]
@kamykn thank you for so fast response!
I tried to do the same thing as you did (launching vim with clean setup) and it seems in this case everything works well. However in my full setup problem is still appears but not every time (I will show it on the GIF). At this point I don't really understand where problem could come from. I also removed spell folder and checked for plugin updates.
![Screen Recording 2020-05-26 at 23 24 50](https://user-images.githubusercontent.com/2991708/82948825-34116280-9fab-11ea-950d-7f617a0f113e.gif)

**Comment by Nodman** [comment]
I think I found the problem. There was another source for spell words
![LWScreenShot 2020-05-26 at 23 53 16](https://user-images.githubusercontent.com/2991708/82949706-bcdcce00-9fac-11ea-9cec-d405597870f6.png)
I don't really understand how vim picked this file but, yeah there was word "chosed" in there, after removing this folder - everything works as expected.

**Comment by kamykn** [comment]
> PS. Still, is there any way to turn off spell check for vim-stratify buffer when using let g:spelunker_check_type = 2

Unfortunately, there is no way to turn off spell check in vim-startify.
So far, I haven't found any ideas to solve this.
