### ISSUE TITLE
Ignore email-like words

### ISSUE THREAD

**Issue by nitnelave** [kamykn/spelunker.vim#47]
I'd like an option to be able to ignore email-like words, i.e. words that have a '@' somewhere in the text.

E.g.: "email@domain.com", "nick@", "@nick" should all be ignored

Rationale: emails are often not dictionary words, and in many contexts '@' marks a reference to a person's username.
It might be necessary to separate the email from the prefix/suffix '@', in order to support use cases like checking annotations in Java `@Annotation`.

Related to https://github.com/kamykn/spelunker.vim/issues/34

**Comment by kamykn** [comment]
Hi, @nitnelave.
I've added a new option to the plugin to ignore words in email format.

```
" Disable email-like words checking. (default: 0)
let g:spelunker_disable_email_checking = 1
```

Could you please update the plugin and then try the new option!

**Comment by nitnelave** [comment]
Thanks, I'll give it a try!

**Comment by nitnelave** [comment]
So, it seems that the email style "bla@bla" is correctly ignored, but I still see "@bla" and "bla@" marked as misspelled.

**Comment by kamykn** [comment]
I've never seen a situation where the @ is treated as a prefix or suffix pattern as an email. I didn't include them in this option because they are often used to represent account names on the websites.

I could add the option to exclude it as an account name, but it would exclude Java annotations as well. Spelunker.vim doesn't parse the text so it can't determine if it is an annotation or not.

**Comment by nitnelave** [comment]
Yes, the point is that most account names are not spelled correctly according to the plugin :)

As for the Java annotations, I'd add a note in the documentation with an autocmd showing how to disable the option locally for java.

**Comment by kamykn** [comment]
@nitnelave 
I've added a new option to the plugin to disable checking account name.

```
" Disable account name checking. (default: 0)
let g:spelunker_disable_account_name_checking = 1
```

Could you check the new option?

**Comment by nitnelave** [comment]
Thanks for the quick update! I'll check that tomorrow, I have to run.

**Comment by nitnelave** [comment]
Works like a charm! Thanks a lot for the quick responses, I really appreciate it :)
