### ISSUE TITLE
Doesn't highlight any misspelled words

### ISSUE THREAD

**Issue by yokoyama-flogics** [kamykn/spelunker.vim#63]
Hello,

Thank you for the great software.
I'm using this for (not-supported yet?) Python, and I'm pretty satisfied.

I had a problem that spelunker.vim doesn't highlight **any** misspelled words in the buffer.
Even I explicitly specified the followings in .vimrc, the specified highlights are ignored.

```vim
highlight SpelunkerSpellBad cterm=underline ctermfg=247 gui=underline guifg=#9e9e9e
highlight SpelunkerComplexOrCompoundWord cterm=underline ctermfg=NONE gui=underline guifg=NONE
```

When I executed the command :highlight in the editor, I saw the followings.

```
SpelunkerSpellBad xxx cleared
SpelunkerComplexOrCompoundWord xxx cleared
```

After some struggles, I finally resolved the problem by changing the above to the followings, by referring this [site](https://vi.stackexchange.com/questions/3355/why-do-custom-highlights-in-my-vimrc-get-cleared-or-reset-to-default).

```vim
autocmd ColorScheme *
    \ highlight SpelunkerSpellBad cterm=underline ctermfg=247 gui=underline guifg=#9e9e9e |
    \ highlight SpelunkerComplexOrCompoundWord cterm=underline ctermfg=NONE gui=underline guifg=NONE
```

My Vim version is 8.2 and which was installed by `homebrew macvim` to macOS 10.15.7.

I could resolve the problem, but I'm curious to know if this occurs only for me.

Regards,
Atsushi

**Comment by KSR-Yasuda** [comment]
I experiences the same issue.

So, created a patch to reset the highlighting on every spellcheck turning on (https://github.com/kamykn/spelunker.vim/pull/70).

With this patch, I think it goes well with spellcheck turning off and on again, at least.

Probably someone is killing the `SpelunkerSpellBad` highlight unexpectedly,
but I have no idea what is the root cause.

**Comment by yokoyama-flogics** [comment]
Hello,

Thank you for the confirmation of the issue, and the patch!!

The spelunker.vim is a must tool for me, and recommending to my colleagues.

Regards,
Atsushi

**Comment by Mochitto** [comment]
Hey there! I've had the same problem and sadly the patch doesn't seem to work (building from your project).
@yokoyama-flogics work-around/fix seems to work for now... Hopefully the maintainers can take a look at this issue again and consider the patch :)

Thank you both for providing some solutions, I find this tool very useful.
