### ISSUE TITLE
Pressing <Esc> (or <Enter>) does not cancel (replaces with the last suggestion instead)

### ISSUE THREAD

**Issue by GabrielDuarteM** [kamykn/spelunker.vim#7]
When I press `Zl` and `<Esc>` (or `<Enter>`, without specifying an option), instead of canceling as one would expect (and as it says on the prompt), it selects the last suggestion and replaces the word with it.

You can see below, first I used `<Esc>`, and the second time, `<Enter>`, and both yielded the same results.

![Peek 2019-06-16 04-13](https://user-images.githubusercontent.com/7675500/59558212-3e7e5a80-8fed-11e9-924e-d014e93e7083.gif)

**Comment by kamykn** [comment]
Thank you for your reporting.
It was a simple bug, so I fixed it with 1f1c22cf74bb39bb07cd5560e180d8728af08a9f.

Please update plugin and Check if the problem is fixed.

**Comment by GabrielDuarteM** [comment]
It's fixed, thanks!
