### ISSUE TITLE
Disable for filetypes or file extensions

### ISSUE THREAD

**Issue by dbatten5** [kamykn/spelunker.vim#73]
Apologies if this is already in the README, I did have a read through but couldn't find it.

I can see there's a section on enabling spelunker for particular filetypes / file extensions, but how can I do the opposite? i.e have spelunker run for all filetypes except given ones.

**Comment by KSR-Yasuda** [comment]
How's setting `b:enable_spelunker_vim` ?

Spellcheck flags are
`g:enable_spelunker_vim` for global          (toggled by `ZT`), and
`b:enable_spelunker_vim` for buffer specific (toggled by `Zt` and `ZT`).

See `autoload/spelunker/toggle.vim` [`spelunker#toggle#toggle()`](https://github.com/kamykn/spelunker.vim/blob/a0bc530f62798bbe053905555a4aa9ed713485eb/autoload/spelunker/toggle.vim#L11) and [`spelunker#toggle#toggle_buffer()`](https://github.com/kamykn/spelunker.vim/blob/a0bc530f62798bbe053905555a4aa9ed713485eb/autoload/spelunker/toggle.vim#L32).

It sets to call spellcheck function for all files as `augroup spelunker`, in [`spelunker.vim`](https://github.com/kamykn/spelunker.vim/blob/a0bc530f62798bbe053905555a4aa9ed713485eb/plugin/spelunker.vim#L293)
(The manner [`README.md`](https://github.com/kamykn/spelunker.vim/blob/master/README.md#22-options) describes is overwriting this).

So I think you should leave the `augroup spelunker` as it is,
and set `b:enable_spelunker_vim` in another `augroup`.

```vim
augroup spelunkerFileTypeSwitch
    autocmd!
    autocmd BufNewFile,BufRead *.ext let b:enable_spelunker_vim = 0
augroup END
```

This `b:enable_spelunker_vim` setting is of course changed by `Zt` or `ZT` on the buffer.

**Comment by dbatten5** [comment]
yes! that works perfectly, thanks @KSR-Yasuda
