### ISSUE TITLE
whitelisted word is highlighted

### ISSUE THREAD

**Issue by FatBoyXPC** [kamykn/spelunker.vim#8]
It looks like `gmstrftime` is in the php whitelist, but it's still getting highlighted for me:

![image](https://user-images.githubusercontent.com/744962/63060357-f9c55180-bebf-11e9-9991-a233836a6cfb.png)

**Comment by kamykn** [comment]
I'm sorry.
This is a bug added when refactoring last time.
This has been fixed so please try to update.

**Comment by FatBoyXPC** [comment]
All is good, thanks!
