### ISSUE TITLE
How to remove whitelisted words

### ISSUE THREAD

**Issue by reineyurkowski** [kamykn/spelunker.vim#85]
Hello, sorry for the bother but when attempting to use this plugin i attempted to show the suggestions but pulled a small brain and accidentally added an incorrect word. and after trying for approximately an hour i've failed to properly understand how to remove a whitelisted word.

i have attempted to look in:
``~/.local/share/nvim/site/pack/packer/start/spelunker.vim/autoload/spelunker/white_list.vim``,
``~/.local/share/nvim/site/pack/packer/start/spelunker.vim/after/plugin/ctrlp/spelunker.vim``,
and removed the words withing the file:
``~/.config/nvim/spell/en.utf-8.add``

i've also attempted uninstalling and reinstalling spelunker (i use PackerSync) and after doing all of these incorrect words i accidentally addded are still being whitelisted. 

might there be another way to do so that i'm potentially missing?

**Comment by KSR-Yasuda** [comment]
@reineyurkowski You mean that you'd like to remove `Zg` or `ZG`-ed words?

Spelunker's spellcheck list is using Vim's standard spellcheck feature.
So, you should search about Vim spellcheck.

In detail, try below:

### How to find the target spell check file

```vim
:new
:setl spell     # Set Vim `spell` feature enabled for `:spelldump` command
:spelldump      # Shows spell word list for the buffer
```

For `Zg` (Spelunker's shortcut), `zg` (Vim's), or `:spellgood {word}`  command,
the word is stored into a permanent             spell file (`${HOME}/.vim/spell/en.utf-8.add.spl` etc.).

For `ZG` (Spelunker's),          `zG` (Vim's), or `:spellgood! {word}` command,
the word is stored into an internal (temporary) spell file (`/tmp/v*/*.utf-8.spl` etc.).

### Remove each added word by command

For a permanently             added word,
do `Zug` (Spelunker's shortcut), `zug` (Vim's), or `:spellundo {word}`  command.

For an internally (temporary) added word,
do `ZUG` (Spelunker's),          `zuG` (Vim's), or `:spellundo! {word}` command.

### Remove added words by editing spell file directly

If you know the exact spell file path, you can manage it by hand.

For binary spell files (e.g. `en.utf-8.add.spl`), there exist text spell files (e.g. `en.utf-8.add`).
Open the text ver. file.

To remove words from the file, delete the lines or comment them out with `#`
(The above commands `:spellundo` etc. do `#`-comment-out).

Then, `:write` it, and **do `:mkspell! %`.**
The command `:mkspell` creates a binary spell file from the text file.
Vim uses this binary ver. spell file.

The file `en.utf-8.add` you've removed is, I think, just a text ver. file.
It's not actual Vim spell file, but just for human to edit the word list).

**Comment by reineyurkowski** [comment]
thank you very much~ for some reason the "en.utf-8.add.spl" file only contains "VIMspell2ˇ"
but the combo of 

```vim
:new
:setl spell     # Set Vim `spell` feature enabled for `:spelldump` command
:spelldump      # Shows spell word list for the buffer
```

and

```vim
:spellundo {word} 
```

works great thank you!
