### ISSUE TITLE
Spell correction fails for some words

### ISSUE THREAD

**Issue by trsdln** [kamykn/spelunker.vim#9]
I noticed that spell correction fails for specific words. Here's example:

![splanker-bug](https://user-images.githubusercontent.com/6911494/63325967-eab52800-c333-11e9-99ba-ce2bf03fb2d9.gif)

__UPD__

Used `Zl` shortcut under `pipline` word.

NVIM v0.3.8  & Vi IMproved 8.1.1800

**Comment by dosentmatter** [comment]
@trsdln, have you  changed the mapping of the default `/`? You can check with `:map /`/

**Comment by trsdln** [comment]
@dosentmatter yes, you're right. I have such mapping (specifically `nnoremap / /\v`). However, I cannot reproduce original issue anymore, so closing it...

**Comment by dosentmatter** [comment]
@trsdin oh alright. You probably updated to latest and my PR #46 that fixed it got merged in.
